# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "潮边"
weight = 1


[en]
languageName = "En"
languagedirection = "ltr"
title = "hannah here"
weight = 2
